const express = require("express");
const { protect } = require("../middleware/authmiddleware");
const { createArticle, updateArticle, searchArticles, fetchArticle, deleteArticle, fetchAllArticles } = require("../Controller/ArticleController");
const router = express.Router();
router.post('/create/:authorId', createArticle);
router.put('/articles/:articleId', updateArticle);
router.get('/articles/search', searchArticles);
router.get('/articles/:articleId', fetchArticle);
router.delete('/articles/:articleId',deleteArticle);
router.get('/articles', fetchAllArticles);
module.exports = router;